name: build-ios
on: push
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    
    - name: Build
      shell: sh
      working-directory: ${{runner.workspace}}
      run: ls wrappers
